# SPDX-FileCopyrightText: 2023-2024 MTS PJSC
# SPDX-License-Identifier: Apache-2.0
"""add search_vector with GIN indexed to Transfer table

Revision ID: b9f5c4315bb2
Revises: 0009_create_celery_tables
Create Date: 2024-09-30 14:25:37.264273

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b9f5c4315bb2"
down_revision = "0009_create_celery_tables"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_expression = (
        "to_tsvector('english'::regconfig, "
        "name || ' ' || "
        "COALESCE(json_extract_path_text(source_params, 'table_name'), '') || ' ' || "
        "COALESCE(json_extract_path_text(target_params, 'table_name'), '') || ' ' || "
        "COALESCE(json_extract_path_text(source_params, 'directory_path'), '') || ' ' || "
        "COALESCE(json_extract_path_text(target_params, 'directory_path'), '') || ' ' || "
        "translate(name, './', '  ') || ' ' || "
        "COALESCE(translate(json_extract_path_text(source_params, 'table_name'), './', '  '), '') || ' ' || "
        "COALESCE(translate(json_extract_path_text(target_params, 'table_name'), './', '  '), '') || ' ' || "
        "COALESCE(translate(json_extract_path_text(source_params, 'directory_path'), './', '  '), '') || ' ' || "
        "COALESCE(translate(json_extract_path_text(target_params, 'directory_path'), './', '  '), '')"
        ")"
    )

    op.add_column(
        "transfer",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(sql_expression, persisted=True),
            nullable=False,
        ),
    )
    op.create_index("idx_transfer_search_vector", "transfer", ["search_vector"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_transfer_search_vector", table_name="transfer", postgresql_using="gin")
    op.drop_column("transfer", "search_vector")
    # ### end Alembic commands ###
