# SPDX-FileCopyrightText: 2023-2024 MTS PJSC
# SPDX-License-Identifier: Apache-2.0
"""Add search_vector to Connection table

Revision ID: 554b28d59e70
Revises: 51fa46fb1506
Create Date: 2024-10-11 11:46:47.748853

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "554b28d59e70"
down_revision = "51fa46fb1506"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_expression = (
        "to_tsvector('english'::regconfig, "
        "name || ' ' || "
        "COALESCE(json_extract_path_text(data, 'host'), '') || ' ' || "
        "COALESCE(translate(json_extract_path_text(data, 'host'), '.', ' '), '')"
        ")"
    )
    op.add_column(
        "connection",
        sa.Column("search_vector", postgresql.TSVECTOR(), sa.Computed(sql_expression, persisted=True), nullable=False),
    )
    op.create_index(
        "idx_connection_search_vector",
        "connection",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_connection_search_vector", table_name="connection", postgresql_using="gin")
    op.drop_column("connection", "search_vector")
    # ### end Alembic commands ###
