# SPDX-FileCopyrightText: 2023-2024 MTS PJSC
# SPDX-License-Identifier: Apache-2.0
"""add run type field

Revision ID: 246db1d5ed29
Revises: 554b28d59e70
Create Date: 2024-10-29 03:49:29.745008

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "246db1d5ed29"
down_revision = "554b28d59e70"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run", sa.Column("type", sa.String(64), nullable=False))
    op.create_index(op.f("ix__run__type"), "run", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__run__type"), table_name="run")
    op.drop_column("run", "type")
    # ### end Alembic commands ###
