version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - make
  tools:
    python: '3.13'
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH python -m pip install uv
    post_install:
      # avoid instaling worker dependencies
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --no-install-project --extra server --extra scheduler --group docs
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv pip install --no-deps sphinx-plantuml # remove after https://github.com/zqmillet/sphinx-plantuml/pull/4
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m pip list -v
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH make docs-openapi

sphinx:
  configuration: docs/conf.py
