# SPDX-FileCopyrightText: 2023-present MTS PJSC
# SPDX-License-Identifier: Apache-2.0
from typing import Literal

from pydantic import model_validator
from pydantic_settings import BaseSettings


class TestSettings(BaseSettings):
    TEST_POSTGRES_HOST_FOR_CONFTEST: str
    TEST_POSTGRES_PORT_FOR_CONFTEST: int
    TEST_POSTGRES_HOST_FOR_WORKER: str
    TEST_POSTGRES_PORT_FOR_WORKER: int
    TEST_POSTGRES_DB: str
    TEST_POSTGRES_USER: str
    TEST_POSTGRES_PASSWORD: str
    TEST_POSTGRES_ADDITIONAL_PARAMS: dict = {}

    TEST_ORACLE_HOST_FOR_CONFTEST: str
    TEST_ORACLE_PORT_FOR_CONFTEST: int
    TEST_ORACLE_HOST_FOR_WORKER: str
    TEST_ORACLE_PORT_FOR_WORKER: int
    TEST_ORACLE_USER: str
    TEST_ORACLE_PASSWORD: str
    TEST_ORACLE_SID: str | None = None
    TEST_ORACLE_SERVICE_NAME: str | None = None
    TEST_ORACLE_ADDITIONAL_PARAMS: dict = {}

    TEST_CLICKHOUSE_HOST_FOR_CONFTEST: str
    TEST_CLICKHOUSE_PORT_FOR_CONFTEST: int
    TEST_CLICKHOUSE_HOST_FOR_WORKER: str
    TEST_CLICKHOUSE_PORT_FOR_WORKER: int
    TEST_CLICKHOUSE_USER: str
    TEST_CLICKHOUSE_PASSWORD: str
    TEST_CLICKHOUSE_DB: str
    TEST_CLICKHOUSE_ADDITIONAL_PARAMS: dict = {}

    TEST_MSSQL_HOST_FOR_CONFTEST: str
    TEST_MSSQL_PORT_FOR_CONFTEST: int
    TEST_MSSQL_HOST_FOR_WORKER: str
    TEST_MSSQL_PORT_FOR_WORKER: int
    TEST_MSSQL_USER: str
    TEST_MSSQL_PASSWORD: str
    TEST_MSSQL_DB: str
    TEST_MSSQL_ADDITIONAL_PARAMS: dict = {}

    TEST_MYSQL_HOST_FOR_CONFTEST: str
    TEST_MYSQL_PORT_FOR_CONFTEST: int
    TEST_MYSQL_HOST_FOR_WORKER: str
    TEST_MYSQL_PORT_FOR_WORKER: int
    TEST_MYSQL_USER: str
    TEST_MYSQL_PASSWORD: str
    TEST_MYSQL_DB: str | None = None
    TEST_MYSQL_ADDITIONAL_PARAMS: dict = {}

    TEST_HIVE_CLUSTER: str
    TEST_HIVE_USER: str
    TEST_HIVE_PASSWORD: str

    TEST_ICEBERG_REST_CATALOG_URL_FOR_CONFTEST: str
    TEST_ICEBERG_REST_CATALOG_URL_FOR_WORKER: str
    TEST_ICEBERG_S3_WAREHOUSE_PATH: str
    TEST_ICEBERG_S3_REGION: str
    TEST_ICEBERG_S3_BUCKET_STYLE: Literal["domain", "path"] = "path"
    TEST_ICEBERG_S3_ADDITIONAL_PARAMS: dict = {}

    TEST_HDFS_HOST: str
    TEST_HDFS_WEBHDFS_PORT: int
    TEST_HDFS_IPC_PORT: int

    TEST_S3_HOST_FOR_CONFTEST: str
    TEST_S3_PORT_FOR_CONFTEST: int
    TEST_S3_HOST_FOR_WORKER: str
    TEST_S3_PORT_FOR_WORKER: int
    TEST_S3_BUCKET: str
    TEST_S3_BUCKET_STYLE: Literal["domain", "path"] = "path"
    TEST_S3_REGION: str
    TEST_S3_ACCESS_KEY: str
    TEST_S3_SECRET_KEY: str
    TEST_S3_PROTOCOL: str = "http"
    TEST_S3_ADDITIONAL_PARAMS: dict = {}

    TEST_SFTP_HOST_FOR_CONFTEST: str
    TEST_SFTP_PORT_FOR_CONFTEST: int
    TEST_SFTP_HOST_FOR_WORKER: str
    TEST_SFTP_PORT_FOR_WORKER: int
    TEST_SFTP_USER: str
    TEST_SFTP_PASSWORD: str

    TEST_FTP_HOST_FOR_CONFTEST: str
    TEST_FTP_PORT_FOR_CONFTEST: int
    TEST_FTP_HOST_FOR_WORKER: str
    TEST_FTP_PORT_FOR_WORKER: int
    TEST_FTP_USER: str
    TEST_FTP_PASSWORD: str

    TEST_FTPS_HOST_FOR_CONFTEST: str
    TEST_FTPS_PORT_FOR_CONFTEST: int
    TEST_FTPS_HOST_FOR_WORKER: str
    TEST_FTPS_PORT_FOR_WORKER: int
    TEST_FTPS_USER: str
    TEST_FTPS_PASSWORD: str

    TEST_SAMBA_HOST_FOR_CONFTEST: str
    TEST_SAMBA_PORT_FOR_CONFTEST: int | None = None
    TEST_SAMBA_HOST_FOR_WORKER: str
    TEST_SAMBA_PORT_FOR_WORKER: int | None = None
    TEST_SAMBA_DOMAIN: str = ""
    TEST_SAMBA_PROTOCOL: str
    TEST_SAMBA_UID: int
    TEST_SAMBA_GID: int
    TEST_SAMBA_SHARE: str
    TEST_SAMBA_USER: str
    TEST_SAMBA_PASSWORD: str
    TEST_SAMBA_AUTH_TYPE: str = "NTLMv2"

    TEST_WEBDAV_HOST_FOR_CONFTEST: str
    TEST_WEBDAV_PORT_FOR_CONFTEST: int
    TEST_WEBDAV_HOST_FOR_WORKER: str
    TEST_WEBDAV_PORT_FOR_WORKER: int
    TEST_WEBDAV_PROTOCOL: str = "http"
    TEST_WEBDAV_USER: str
    TEST_WEBDAV_PASSWORD: str

    @model_validator(mode="before")
    def check_sid_and_service_name(cls, values):
        sid = values.get("TEST_ORACLE_SID")
        service_name = values.get("TEST_ORACLE_SERVICE_NAME")
        if (sid is None) == (service_name is None):
            raise ValueError("Connection must have one param: sid or service name")
        return values
