name: PyPI release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    if: github.repository == 'MTSWebServices/syncmaster' # prevent running on forks

    environment:
      name: pypi
      url: https://pypi.org/p/data-syncmaster

    permissions:
      id-token: write # to auth in PyPI
      contents: write # to create Github release

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: 'false'

      - name: Generate OpenAPI Schema
        run: |
          uv sync --frozen --extra server
          make docs-openapi

      - name: Fix logo in Readme
        run: |
          sed -i "s#image:: mddocs/docs/#image:: https://raw.githubusercontent.com/MTSWebServices/syncmaster/$GITHUB_SHA/mddocs/docs/#g" README.rst
          sed -i "s#logo_wide_red_text.svg#logo_wide.svg#g" README.rst

      - name: Patch version template
        # Due to change above, git stage area is dirty, so we need to patch the template
        run: sed -i 's#dirty_template = ".*"#dirty_template = "{tag}"#' pyproject.toml

      - name: Build package
        run: uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Generate SBOM
        run: |
          uv pip install cyclonedx-bom
          uv export --all-extras --format requirements.txt | uv run cyclonedx-py requirements - > sbom.cyclonedx.json

      - name: Prepare changelog
        id: release-name
        run: |
          cat mddocs/docs/changelog/${GITHUB_REF_NAME}.md > changelog.md
          # Remove anchors like "{ #syncmaster-changelog-0-3-4 }"
          sed -i -E 's/\{.*\}//g' changelog.md
          # Header looks like "## [0.3.4](...) - 2026-05-26"
          # Release name looks like "0.3.4 - 2026-05-26"
          echo -n name= > "$GITHUB_OUTPUT"
          cat changelog.md | head -1 | sed -E "s/#+\s*//g" >> "$GITHUB_OUTPUT"
          # Remove header with release name
          sed -i -e '1,2d' changelog.md

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: ${{ steps.release-name.outputs.name }}
          body_path: changelog.md
          files: |
            dist/*.tar.gz
            dist/*.whl
            mddocs/docs/_static/openapi.json
            sbom.cyclonedx.json
