name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  tests:
    name: Run tests (Python 3.11, Pydantic v1 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_VERSION: 1.7.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start docker compose
        run: |
          docker compose -f ./docker-compose.test.yml down -v --remove-orphans
          docker compose -f ./docker-compose.test.yml up -d --wait --wait-timeout 200
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster

      - name: Build Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          tags: syncmaster_backend:${{ github.sha }}
          file: docker/worker.dockerfile
          load: true
          cache-to: type=gha,mode=max
          cache-from: type=gha

      - name: Run Tests
        uses: tj-actions/docker-run@v2
        with:
          image: syncmaster_backend:${{ github.sha }}
          name: backend
          options: --net syncmaster_network --env-file ./.env.docker --rm
          args: |
            cd /syncmaster
            coverage run -m pytest -vvv -s --ff -x

      - name: Shutdown
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster
