name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  tests:
    name: Run tests (Python 3.11, Pydantic v1 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_VERSION: 1.7.1

    steps:
      - name: Start HDFS
        run: |
          docker compose -f ./docker-compose.test.yml down -v --remove-orphans
          docker compose -f ./docker-compose.test.yml up -d test-hive --wait --wait-timeout 200 &
          wait_pid=$!
          docker compose logs -f test-hive &
          wait $wait_pid
        env:
          HDFS_IMAGE: mtsrus/hadoop:${{ inputs.hadoop-version }}
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-hadoop${{ inputs.hadoop-version }}

      - name: Wait for HDFS to be ready
        run: |
          ./docker/wait-for-it.sh -h localhost -p 9870 -t 60

      - name: Start dependencies
        run: |
          docker compose -f docker-compose.test.yml up -d \
          test-postgres test-s3 test-oracle metastore-hive rabbitmq worker db

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Cache poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-codeql-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-codeql-${{ hashFiles('**/poetry.lock') }}
            ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-codeql-
            ${{ runner.os }}-python
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          poetry install --no-root --with backend,dev,test

      - name: Run Tests
        run: |
          source .env.github
          mkdir -p reports/
          echo "127.0.0.1 test-hive" | sudo tee -a /etc/hosts
          poetry run coverage run -m pytest -vvv -s --ff -x

      - name: Shutdown Backend Container
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-backend
