name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  tests:
    name: Run tests (Python 3.11, Pydantic v1 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_VERSION: 1.6.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show space
        run: |
          df -h
          pwd
          realpath ~/
          ls -lsah ~ || true
          ls -lsah /mnt || true
          ls -lsah /mnt/* || true
          mkdir -p ~/.ivy2/
          mount --bind /mnt/.ivy2/ ~/.ivy2/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache ivy2 pip
        uses: actions/cache@v4
        with:
          path: ~/.ivy2
          key: ivy2

      - name: Try to clean free space
        run: |
          docker system prune -a -f --volumes

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Start docker compose
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
          docker compose -f docker-compose.test.yml up -d --wait --wait-timeout 200
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster

      - name: Run Tests.
        run: |
          docker compose -f docker-compose.test.yml exec -T backend coverage run -m pytest -vvv -s
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster

      - name: Shutdown
        if: always()
        run: |
          df -h
          docker compose -f docker-compose.test.yml down -v --remove-orphans
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster
