name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  tests:
    name: Run tests (Python 3.11, Pydantic v1 on ubuntu-latest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      POETRY_VERSION: 1.6.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Try to clean free space
        run: |
          docker system prune -a -f --volumes

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Start docker compose
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
          docker compose -f docker-compose.test.yml up -d --wait --wait-timeout 200
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster

      - name: Run Tests
        run: |
          docker logs backend
          docker compose -f docker-compose.test.yml exec -T backend /bin/bash coverage run -m pytest -vvv -s --ff -x
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster

      - name: Shutdown
        run: |
          docker compose -f docker-compose.test.yml down -v --remove-orphans
        env:
          COMPOSE_PROJECT_NAME: ${{ github.run_id }}-syncmaster
